# Generated by Django 3.0.10 on 2021-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_unused_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='higher_predict_range',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lower_predict_range',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='predict_value',
            field=models.TextField(default=None, null=True),
        ),
    ]
